### ISSUE TITLE
Split out `core` to be used from Visual Studio code as executable or MS Build task

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/CsToMd#1]
I do not see how I can use tool in my VS Code only workflow. I would be good to have
- .NET Standard 2.0 compatible executable as pre build event
- MS Build task to add to project

Other people seems consider tool not usable for them either
https://github.com/OrleansContrib/SignalR.Orleans/issues/19#issuecomment-431826165

**Comment by dadhi** [comment]
May be we can create a content based nuget package with `.props` file to do both transformation and cs -> md nesting. Hard to tell  will it work without experimentation.

**Comment by dadhi** [comment]
Made it into CLI tool that can be used in a task, see readme.
