### ISSUE TITLE
Question: how is the table of contents created?

### ISSUE THREAD

**Issue by Nednilrev** [dadhi/CsToMd#11]
Hi,
I noticed that your Decorator.cs file contained '[TOC]' and that the output automagically contains the table of contents with all the headers on the page.
How does this work? (sorry for the noob question that may be unrelated to CsToMd, but didn't know where to ask it).

**Comment by dadhi** [comment]
Hi @Nednilrev 

I am not using TOC anymore. It was a custom extension understood by BitBucket wiki but not by GitHub.

Instead I am using the markdown plugin for VSCode ehich has a command **Create Table of Contents..** and **Update Table of Contents**, and also shows the hint when the toc is outdated.

So first I am generating the .md file without the toc, then creating the toc in .md file via plugin, and copy-paste it into the original .cs file.

I will post the gif with the my workflow later and probably add this explanation into the readme.

**Comment by Nednilrev** [comment]
Thanks for the explanation. 
I use the md viewer extension for chrome, which generates a toc automatically, but it's on the left of the page. I prefer it to be in the md itself, though.

**Comment by dadhi** [comment]
@Nednilrev 

Here is the gif ;)

![CsToMd_TOC](https://user-images.githubusercontent.com/39516/94345584-96e53a00-002f-11eb-9923-548e9cfa496a.gif)

**Comment by Nednilrev** [comment]
@dadhi Thanks for the gif and the tip! Will definitely give this plugin a try. So far, I've been using the Mardown Editor plugin.
By the way, love the latest features of your plugin!

**Comment by Nednilrev** [comment]
Just wanted to come back to say that 'Markdown all in one' is only available for Visual Studio Code, and not for Visual Studio 2019.

**Comment by dadhi** [comment]
@Nednilrev Yes. I am lately rarely using the VS.. There is a plugins for VS. But not sure about their TOC capabilities, so my answer would be to have VSCode opened nearby for the TOC.

If you find a more straightforward way, please give me a notice. Thanks.
