### ISSUE TITLE
Cannot find custom tool 'CsToMd' on this system

### ISSUE THREAD

**Issue by Nednilrev** [dadhi/CsToMd#5]
I would love to try out your nifty extension, because it looks very promising, but I get the above error message.
Installed CsToMd via the extension manager in Visual Studio 2019 Professional. Everything looks fine, but for the fact that it doesn't work. All the files seem to be present on my system.
I thought my company antivirus might be interfering, but all other extensions work fine.
Attached is the installation log.
[dd_setup_20200811163223_002_CsToMd.13e98d61-1f50-4acd-8e25-099cf4b733f3.log](https://github.com/dadhi/CsToMd/files/5060961/dd_setup_20200811163223_002_CsToMd.13e98d61-1f50-4acd-8e25-099cf4b733f3.log)
Thanks in advance for any advice.
**Update**: I've tried it on another file, and now the md file IS created, so that's good. HOWEVER, the MD file contains everything in the cs file, and not just the info that is between /*md md*/ tags
**Update**: OK, I figured out that the output is _supposed_ to contain not only the info between the tags, but _everything_ included in the cs file. Should have read the documentation better. Closing this ticket.

**Comment by Nednilrev** [comment]
Trying it on another cs file solved the problem.

**Comment by dadhi** [comment]
Cool!
Interesting to see what will be your feedback.
